a=int(input('First digit'))
b=int(input('Second digit'))

print('Addition =',a+b)
print('Subtraction =',a-b)
print('Division =',a/b)
print('Multiplication =',a*b)
print('Exponent =',a**b)
print('Modulus =',a%b)
print('Floor division =',a//b)
